version: '3'

services:
  postgres:
    image: postgres
    container_name: choosely-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: main
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - main-net

  redis:
    image: redis
    container_name: choosely-redis
    ports:
      - '6379:6379'

  app:
    entrypoint: "air"
    build:
      dockerfile: Dockerfile # Dockerfile name
      context: . # Where Dockerfile is located
      target: dev # Stage of multistage building
    volumes:
      - .:/app # Map this directory to /app directory inside the container
    container_name: choosely-app
    ports:
      - '8080:8080'
    depends_on:
      - postgres
      - redis
    networks:
      - main-net
    command: /app/server
    
volumes:
  db-data: # volume used by postgres service

networks:
  main-net:
    driver: bridge
