// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package persistence

import (
	"database/sql"
)

type Poll struct {
	ID       sql.NullString
	Question sql.NullString
	Options  interface{}
}
