// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: queries.sql

package persistence

import (
	"context"
)

const addPoll = `-- name: AddPoll :exec
INSERT INTO
    polls (id, question)
VALUES
    ("12156146", "How old are you?")
`

func (q *Queries) AddPoll(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, addPoll)
	return err
}
